### ISSUE TITLE
模板中心数据上传预览时，自动换行部分未做还原。【附图】

### ISSUE THREAD

**Issue by wlchair** [iCloudWorkGroup/table#6]
![_ls sjf6 e2 omt f nsxs](https://wt-prj.oss.aliyuncs.com/7d36230da61d4ca5aa5a497986c6ba09/deb9283b-e1df-409d-ab9b-a20656051968.png)
![2](https://wt-prj.oss.aliyuncs.com/7d36230da61d4ca5aa5a497986c6ba09/42e54221-425b-4e18-8b25-bba620e859c5.png)

**Comment by jhrgitgit** [comment]
modify by ZengQu
